import { PersonalInformationForm } from "../../types/ContractsTypes";

export const contractsMock: PersonalInformationForm[] = [
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    },
    {
        Idempresa: "string",
        Prefijo: "string",
        Consecutivo: "string",
        Adiccional: "string",
        Numerocontrato: "string",
        idcategoria: "string",
        idsubcategoria: "string",
        Servicio: "string",
        Idestadocontrato: "string",
        Idsede: "string",
        Numeroorden: "string",
        Idcontratista: "string",
        Fechainiciocontrato: "string",
        Fechafincontrato: "string",
        Idcomprador: "string",
        Idadministrador: "string"
    }
]