import { PersonalInformationForm } from "../../types/EmployeeTypes";

export const employeeMock: PersonalInformationForm[] = [
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "Nuevo",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    },
    {
        FileType: "string",
        ID: "string",
        Documento: "123456",
        Nombres: "Carlos Pitre",
        FechaNaci: "string",
        Genero: "string",
        Escolarida: "string",
        Celular: "string",
        Email: "string",
        Contacto: "string",
        TelefonoContacto: "string",
        EstadoCivil: "string",
        Empresa: "string",
        Sede: "string",
        PayStatus: "string",
        ImagenUr: "https://randomuser.me/api/portraits/men/75.jpg",
        UsuarioCreacion: "string",
        FechaCreacion: "string",
        UsuarioModifica: "string",
        FechaModificacion: "string",
        Bandera: "string"
    }
]