import { Programming } from "../../../types/ProgrammingType";

export const patientsMock: Programming[] = [
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Carlos Pitre",
    EstadoCaso: "Nuevo",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Triage I", "Psicología", "Ergonomia"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jose Guerra",
  },
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Francisco Javier Cardenas Garcia",
    EstadoCaso: "Control",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Psicología"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jorge Rivera",
  },
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Francisco Javier Cardenas Garcia",
    EstadoCaso: "Control",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Psicología"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jorge Rivera",
  },
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Francisco Javier Cardenas Garcia",
    EstadoCaso: "Control",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Psicología"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jorge Rivera",
  },
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Francisco Javier Cardenas Garcia",
    EstadoCaso: "Control",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Psicología"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jorge Rivera",
  },
  {
    ImagenUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    Documento: "123456",
    Nombres: "Francisco Javier Cardenas Garcia",
    EstadoCaso: "Control",
    Contingencia: "Enfermedad General",
    EstadoPac: "Atendido",
    Atencion: ["Psicología"],
    Celular: "3145202614",
    Fecha: "10-10-2021",
    Sede: "PRIBBENOW",
    usuario: "Jorge Rivera",
  }
]